### ISSUE TITLE
Sorting functionality doesn't work

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/nyc-accessible-restaurant-advisor#146]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

As a Normal User if I go to restaurants page and try to sort nothing happens.

## Expected Behavior

It should sort by as per the chosen option

## Current Behavior

It doesn't sort

## Steps to Reproduce

1. Login as nu_test1
2. Navigate to restaurant listings page
3. Sort it by any option.
4. The results order doesn't change at all

**Before Sort**
![image](https://user-images.githubusercontent.com/55005259/100248557-3f652c80-2f01-11eb-9f52-cb737e459a54.png)

**After Sort**
![image](https://user-images.githubusercontent.com/55005259/100248653-5a37a100-2f01-11eb-82f8-b86ee352ab55.png)

**Comment by shrutiagarwal28** [comment]
I came across the same bug. The team could probably use AJAX to update parts of their webpage without having to reload the whole webpage.
