### ISSUE TITLE
The website uses an insecure protocol http

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/nyc-accessible-restaurant-advisor#148]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The website uses an insecure protocol http

## Expected Behavior

The website should use https which is more secure and by default comes in heroku.

## Current Behavior

The website uses an insecure protocol http
URL: 
http://accessible-nyc-main.herokuapp.com/
## Steps to Reproduce

![image](https://user-images.githubusercontent.com/55005259/100250373-383f1e00-2f03-11eb-9971-057a13694e8b.png)

**Comment by rossy312** [comment]
Thanks for pointing this out. What browser were you using?

**Comment by gauravag2207** [comment]
I tried in Chrome.
