### ISSUE TITLE
Page title comes with tags on about us page

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/nyc-accessible-restaurant-advisor#149]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

The page title comes with tags on about us page

## Expected Behavior

No tags should appear

## Current Behavior

<title> tag comes

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/55005259/100250598-750b1500-2f03-11eb-9007-a13d52b5b100.png)

**Comment by rossy312** [comment]
Thank you for pointing this out. However, this is our old UI so we are not going to address this issue.
