### ISSUE TITLE
Suggestion: Display sucess alert in the page instead of raising window alerts on updating profile. 

### ISSUE THREAD

**Issue by gsavitha** [gcivil-nyu-org/nyc-accessible-restaurant-advisor#156]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Window alert raised on form submit instead of in-page alerts.

## Expected Behavior
Display success messages in page.
## Current Behavior
Window alert raised.

## Ideas for Improvement
https://getbootstrap.com/docs/4.0/components/alerts/
## Steps to Reproduce

1. Log In as restaurant owner
2. Update Profile Image
![image](https://user-images.githubusercontent.com/17599828/100278882-8a983300-2f33-11eb-8644-05d73080f5ca.png)

3. Alert Raised
![image](https://user-images.githubusercontent.com/17599828/100278869-81a76180-2f33-11eb-92de-9f357b07d83c.png)

**Comment by rossy312** [comment]
Thanks for the feedback, however, we have decided to keep as is.
