### ISSUE TITLE
Nav Bar design changes with different sections and UI for profiles is significantly different from website theme

### ISSUE THREAD

**Issue by shrutiagarwal28** [gcivil-nyu-org/nyc-accessible-restaurant-advisor#169]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

1. I feel that the Nav Bar design should remain consistent throughout the website.
2. It would be nice to see the webpage design for the profile/edit profile webpage match the design theme of the rest of the website.

## Current Behavior

1. Nav bar design changes completely for profiles and FAQ sections
2. Currently the profiles section  has a green theme which is not present for the rest of the website and the font style is significantly different too. 

## Steps to Reproduce

1. I think if you use base.html it would help have a uniform front-end template across the site
2.
3.
4.

**Comment by DarkBruce** [comment]
Thank you for your comment. We're in the middle of improving overall theme for our UI. We'll make the navigation bar identical for all the pages before the final demo.
