### ISSUE TITLE
Unable to Login with nu_test5

### ISSUE THREAD

**Issue by joshganguly** [gcivil-nyu-org/nyc-accessible-restaurant-advisor#170]
Unable to Login with nu_test5 and given password

## Expected Behavior
Should be able to Login with accounts provided

## Current Behavior
Unable to Login with nu_test5 and given password

![Screen Shot 2020-11-25 at 8 42 00 PM (2)](https://user-images.githubusercontent.com/12211050/100298286-bc72bf00-2f5e-11eb-8cfc-1c9bfe019b67.png)

**Comment by rossy312** [comment]
Thanks for letting us know. Another group changed the username for the nu_test5 account.
